//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsDapperProject.DataAccess.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarsDapperProject.DataAccess.Scripts.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO 
        ///    brands (name) 
        ///VALUES
        ///    (@name)
        ///RETURNING id.
        /// </summary>
        internal static string AddBrand {
            get {
                return ResourceManager.GetString("AddBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO 
        ///    cars (model, brand_id, owner_id) 
        ///VALUES
        ///    (@model, @brand_id, @owner_id)
        ///RETURNING id.
        /// </summary>
        internal static string AddCar {
            get {
                return ResourceManager.GetString("AddCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO 
        ///	owners (name, phone, email)
        ///VALUES 
        ///	(@name, @phone, @email)
        ///RETURNING id.
        /// </summary>
        internal static string AddOwner {
            get {
                return ResourceManager.GetString("AddOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM brands 
        ///WHERE id = @id.
        /// </summary>
        internal static string DeleteBrand {
            get {
                return ResourceManager.GetString("DeleteBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM cars
        ///WHERE id = @id.
        /// </summary>
        internal static string DeleteCar {
            get {
                return ResourceManager.GetString("DeleteCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM owners
        ///WHERE id = @id.
        /// </summary>
        internal static string DeleteOwner {
            get {
                return ResourceManager.GetString("DeleteOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    id,
        ///    name
        ///FROM brands.
        /// </summary>
        internal static string GetAllBrands {
            get {
                return ResourceManager.GetString("GetAllBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    c.id,
        ///    c.model,
        ///    c.owner_id AS &quot;OwnerId&quot;,
        ///    o.name AS &quot;OwnerName&quot;
        ///FROM cars c
        ///LEFT JOIN owners o ON c.owner_id = o.id
        ///WHERE c.brand_id = @brand_id.
        /// </summary>
        internal static string GetAllCarsByBrand {
            get {
                return ResourceManager.GetString("GetAllCarsByBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    c.model,
        ///    b.name AS &quot;Brand&quot;
        ///FROM cars c
        ///INNER JOIN brands b ON c.brand_id = b.id
        ///WHERE c.owner_id = @owner_id.
        /// </summary>
        internal static string GetAllCarsByOwner {
            get {
                return ResourceManager.GetString("GetAllCarsByOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	id,
        ///	name,
        ///	phone,
        ///	email
        ///FROM owners
        ///WHERE id = @id.
        /// </summary>
        internal static string GetAllOwners {
            get {
                return ResourceManager.GetString("GetAllOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	id, 
        ///	name 
        ///FROM brands
        ///WHERE id = @id.
        /// </summary>
        internal static string GetBrandById {
            get {
                return ResourceManager.GetString("GetBrandById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    c.id,
        ///    c.model,
        ///    c.brand_id AS &quot;BrandId&quot;,
        ///    c.owner_id AS &quot;OwnerId&quot;,
        ///	b.name AS &quot;BrandName&quot;,
        ///    o.name AS &quot;OwnerName&quot;
        ///FROM cars c
        ///INNER JOIN brands b ON c.brand_id = b.id
        ///LEFT JOIN owners o ON c.owner_id = o.id
        ///WHERE c.id = @id.
        /// </summary>
        internal static string GetCarById {
            get {
                return ResourceManager.GetString("GetCarById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	id,
        ///	name,
        ///	phone,
        ///	email
        ///FROM owners
        ///WHERE id = @id.
        /// </summary>
        internal static string GetOwnerWithCarById {
            get {
                return ResourceManager.GetString("GetOwnerWithCarById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT EXISTS(
        ///	SELECT id 
        ///	FROM brands
        ///	WHERE id = @id).
        /// </summary>
        internal static string IsBrandByIdExists {
            get {
                return ResourceManager.GetString("IsBrandByIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT EXISTS (
        ///	SELECT id 
        ///	FROM owners
        ///	WHERE id = @id).
        /// </summary>
        internal static string IsOwnerByIdExists {
            get {
                return ResourceManager.GetString("IsOwnerByIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE brands
        ///SET
        ///	name = COALESCE(@name, name)
        ///WHERE id = @id.
        /// </summary>
        internal static string UpdateBrand {
            get {
                return ResourceManager.GetString("UpdateBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE cars
        ///SET 
        ///	model = COALESCE(@model, model), 
        ///	brand_id = COALESCE(@brand_id, brand_id), 
        ///	owner_id = COALESCE(@owner_id, owner_id) 
        ///WHERE id = @id.
        /// </summary>
        internal static string UpdateCar {
            get {
                return ResourceManager.GetString("UpdateCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE owners
        ///SET 
        ///	name = COALESCE(@name, name),
        ///	phone = COALESCE(@phone, phone),
        ///	email = COALESCE(@email, email)
        ///WHERE id = @id.
        /// </summary>
        internal static string UpdateOwner {
            get {
                return ResourceManager.GetString("UpdateOwner", resourceCulture);
            }
        }
    }
}
